version: '3.12'

services:
  HW4:
    image: hw4
    build:
      context: .
      dockerfile: ./docker_files/Dockerfile.HW4
    container_name: hw4
    ports:
      - "80:80"
    environment:
      - PYTHONPATH=/HW4

    command: uvicorn HW4.demo_service.api.main:app --host 0.0.0.0 --port 80

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  locust:
      image: locustio/locust
      ports:
        - "8089:8089"
      volumes:
        - ./HW4/tests_hw4/locust:/mnt/locust
      command: -f /mnt/locust/locustfile.py --host http://HW4:80
      environment:
        - PIP_EXTRA_INDEX_URL=https://pypi.org/simple
      entrypoint: /bin/sh -c "pip install prometheus_client && locust -f /mnt/locust/locustfile.py --host http://fastapi:8000"