version: '3'

services:
  HW2:
    image: testapp:latest
    build:
      context: .
      dockerfile: ./PythonBackendAITH/docker_files/Dockerfile.HW2
    container_name: test_app
    ports:
      - "80:80"
    environment:
      - PYTHONPATH=/HW2

    command: uvicorn HW2.shop_api.main:app --host 0.0.0.0 --port 80

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
